export const namesArticulo33 = [
  "ÚLTIMO PÁRRAFO",
  "I. El marco normativo aplicable al sujeto obligado",
  "II. Su estructura orgánica completa",
  "III. Las facultades de cada área",
  "IV. Las metas y objetivos de las áreas de conformidad con sus programas operativos",
  "V. Los indicadores relacionados con temas de interés público o trascendencia social",
  "VI. Los indicadores que permitan rendir cuenta de sus objetivos y resultados",
  "VII. El directorio de todos los servidores públicos",
  "VIII. La remuneración bruta y neta de todos los servidores públicos de base o de confianza",
  "IX. Los gastos de representación y viáticos, así como el objeto e informe de comisión correspondiente",
  "X. El número total de las plazas y del personal de base y confianza",
  "XI. Las contrataciones de servicios profesionales por honorarios",
  "XII. La versión pública de las declaraciones patrimoniales de los servidores público",
  "XIII. El domicilio de la Unidad de Transparencia",
  "XIV. Las convocatorias a concursos para ocupar cargos públicos y los resultados de los mismos",
  "XV. La información de los programas de subsidios, estímulos y apoyos",
  "XVI. Las condiciones generales de trabajo, contratos o convenios",
  "XVII. La información curricular desde el nivel de jefe de departamento o equivalente, hasta el titular del sujeto obligado",
  "XVIII. El listado de servidores públicos con sanciones administrativas definitivas",
  "XIX. Los servicios que ofrecen señalando los requisitos para acceder a ellos",
  "XX. Los trámites, requisitos y formatos que ofrecen",
  "XXI. La información financiera sobre el presupuesto asignado, así como los informes de su ejecución",
  "XXII. La información relativa a la deuda pública",
  "XXIII. Los montos destinados a gastos relativos a comunicación social y publicidad oficial",
  "XXIV. Los informes de resultados de las auditorías al ejercicio presupuestal",
  "XXV. El resultado de la dictaminación de los estados financieros",
  "XXVI. Los montos, criterios, convocatorias y listado de personas físicas o morales",
  "XXVII. Las concesiones, contratos, convenios, permisos, licencias o autorizaciones otorgadas",
  "XXVIII. La información sobre los resultados sobre procedimientos de adjudicación directa",
  "XXIX. Los informes que por disposición legal generen los sujetos obligados",
  "XXX. Las estadísticas que generen en cumplimiento de sus facultades, competencias o funciones",
  "XXXI. Informe de avances programáticos o presupuestales, balances generales y su estado financiero",
  "XXXII. Padrón de proveedores y contratistas",
  "XXXIII. Los convenios de coordinación que celebren con la federación, otros estados o municipios, partidos políticos, instituciones de enseñanza o cualquier organización",
  "XXXIV. El inventario de bienes muebles e inmuebles en posesión y propiedad",
  "XXXV. Las recomendaciones emitidas por los órganos públicos del Estado mexicano u organismos internacionales garantes de los derechos humanos",
  "XXXVI. Las resoluciones y laudos que se emitan en procesos o procedimientos seguidos en forma de juicio",
  "XXXVII. Los mecanismos de participación ciudadana",
  "XXXVIII. Los programas que ofrecen, incluyendo información sobre la población, objetivo y destino, así como los trámites",
  "XXXIX. Las actas y resoluciones del Comité de Transparencia de los sujetos obligados",
  "XL. Todas las evaluaciones y encuestas que hagan los sujetos obligados a programas financiados con recursos públicos",
  "XLI. Los estudios financiados con recursos públicos",
  "XLII. El listado de jubilados y pensionados y el monto que reciben",
  "XLIII. Los ingresos recibidos por cualquier concepto",
  "XLIV. Donaciones hechas a terceros en dinero o en especie",
  "XLV. El catálogo de disposición y guía de archivo documental",
  "XLVI. Las actas de sesiones ordinarias y extraordinarias, así como las opiniones y recomendaciones que emitan",
  "XLVII. Para efectos estadísticos, el listado de solicitudes a las empresas concesionarias de telecomunicaciones y proveedores de servicios o aplicaciones de Internet",
  "XLVIII. El seguimiento de las obligaciones de responsabilidad hacendaria",
  "XLIX. Cualquier otra información que sea de utilidad o se considere relevante"
];
